# Model Configuration
model:
    arch: hardnet

# Data Configuration
data:
    dataset: ade20k 
    train_split: training
    val_split: validation
    img_rows: 300
    img_cols: 300
    path: /home/socialab/FCHarDNet/ADE20K/ADE20K_2016_07_26/


# Training Configuration
training:
    n_workers: 2
    train_iters: 10
    batch_size: 1
    val_interval: 5
    print_interval: 1
    loss:
        name: cross_entropy
# options: 'cross_entropy, bootstrapped_cross_entropy, multi_scale_crossentropy']


    # Optmizer Configuration
    optimizer:
        name: sgd
# [options: 'sgd, adam, adamax, asgd, adadelta, adagrad, rmsprop']
        lr: 0.01
        weight_decay: 0.0005
        momentum: 0.9


    # LR Schedule Configuration
    lr_schedule:
        name: poly_lr 
#[options: 'constant_lr, poly_lr, multi_step, cosine_annealing, exp_lr']
        max_iter: 100

    # Resume from checkpoint  
    resume: None
    finetune: None
